# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:10.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: update yarn
          command: sudo npm install yarn@1.13.0 --global
      - restore_cache:
          keys:
            - v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: run linters
          command: yarn lint

  test:
    docker:
      - image: circleci/node:10.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: update yarn
          command: sudo npm install yarn@1.13.0 --global
      - restore_cache:
          keys:
            - v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: run tests
          command: yarn test --maxWorkers 2
      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  production:
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "fa:1a:59:c0:b3:7e:7d:a5:65:3c:78:94:06:d3:f3:9f"
      - run:
          name: install heroku
          command: |
            bash .circleci/setup-heroku.sh
      - deploy:
          name: Deploy Master to Production Heroku
          command: |
            git remote add heroku https://git.heroku.com/terminal-uniswap.git
            git push -f heroku master

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
      - production:
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - master
